# Play with NumPy Arrays

In [1]:
import numpy as np

In [2]:
np.array([3, 5, 8, 17])

array([ 3,  5,  8, 17])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.zeros(3)

array([0., 0., 0.])

np.arange

*Syntax:*
    
np.arange(start, stop, step)

In [5]:
np.arange(4)

array([0, 1, 2, 3])

In [7]:
np.arange(2, 4)

array([2, 3])

In [10]:
np.arange(2, 6, 2)

array([2, 4])

In [11]:
np.arange(2, 6, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

```np.linspace```

*Syntax*

np.linspace(start, stop, num)

default for num is 50

In [12]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [13]:
np.linspace(-1,1,6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [14]:
np.linspace(-1,1,7)

array([-1.        , -0.66666667, -0.33333333,  0.        ,  0.33333333,
        0.66666667,  1.        ])

In [15]:
x_array = np.linspace(-1, 1, 9)

In [16]:
print(x_array)

[-1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.  ]


In [17]:
y_array = x_array**2
print(y_array)

[1.     0.5625 0.25   0.0625 0.     0.0625 0.25   0.5625 1.    ]


In [18]:
z_array = np.sqrt(y_array)
print(z_array)

[1.   0.75 0.5  0.25 0.   0.25 0.5  0.75 1.  ]


In [19]:
add_array = x_array + y_array
print(add_array)

[ 0.     -0.1875 -0.25   -0.1875  0.      0.3125  0.75    1.3125  2.    ]


In [21]:
mult_array = x_array * z_array
print(mult_array)

[-1.     -0.5625 -0.25   -0.0625  0.      0.0625  0.25    0.5625  1.    ]


In [22]:
x_array / y_array

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([-1.        , -1.33333333, -2.        , -4.        ,         nan,
        4.        ,  2.        ,  1.33333333,  1.        ])

In [25]:
my_array = np.arange(4, 81, 2)
print(my_array)

[ 4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50
 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80]


In [26]:
a = np.array([14, 20, 75, 90])
b = np.array([10, 32, 18, 120])
total_array = a + b
print(total_array)

[ 24  52  93 210]


In [27]:
less_array = total_array - 10
print(less_array)

[ 14  42  83 200]


In [28]:
type(less_array)

numpy.ndarray

In [30]:
new_array = np.array([18, 10, 3, 5, 8, 21])
print(new_array)

[18 10  3  5  8 21]


In [31]:
new_array[0]

18

In [32]:
new_array[-1]

21

In [33]:
new_array[0:3]

array([18, 10,  3])

In [45]:
scores = np.array([99, 85, 90, 75, 88])

ab = np.ones(len(scores))
print(ab)

new_scores = scores + 1
print(new_scores)

new_scores = scores + [1,1,1,1,1]
print(new_scores)

new_scores = scores + np.array([1,1,1,1,1])
print(new_scores)

new_scores = scores + ab
print(new_scores)

[1. 1. 1. 1. 1.]
[100  86  91  76  89]
[100  86  91  76  89]
[100  86  91  76  89]
[100.  86.  91.  76.  89.]


In [47]:
array_2d = np.array([[1, 2], [3, 4]])
print(array_2d)

[[1 2]
 [3 4]]


In [48]:
np.shape(array_2d)

(2, 2)

In [50]:
help(np.shape)

Help on function shape in module numpy.core.fromnumeric:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    alen
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



In [53]:
X = np.array([[1, 2], [3, 4]])
Y = np.array([[1, -1], [0, 1]])

In [54]:
print(Y)

[[ 1 -1]
 [ 0  1]]


In [55]:
X + Y

array([[2, 1],
       [3, 5]])

In [56]:
X * Y

array([[ 1, -2],
       [ 0,  4]])

In [57]:
X @ Y

array([[1, 1],
       [3, 1]])

In [58]:
np.dot(X, Y)

array([[1, 1],
       [3, 1]])

In [61]:
X[0, 0]

1

In [62]:
X[:, 0]

array([1, 3])

In [63]:
X[0, :]

array([1, 2])

In [64]:
X / Y

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 1., -2.],
       [inf,  4.]])

In [65]:
a =np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [67]:
a_3d =np.reshape(a, (2, 3, 4))
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [68]:
a_3d[:, :, 0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [69]:
z = a_3d[:, :, 0]
z.shape

(2, 3)

In [70]:
a_3d[:, 0:2, 0]

array([[ 0,  4],
       [12, 16]])