Before you turn in this homework, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you execute every single code cell, in order, filling with your solutions in any place that says `YOUR CODE HERE`, and always DELETE the line that says:

```python
raise NotImplementedError()
```
The purpose of this line is to tell you if you forgot to answer a question (it will throw an error if the line is there)

**IMPORTANT**: DO NOT DELETE ANY CELL.

Fill your name below:

In [1]:
NAME = "Zeyu Liu"

## Before you start 

For this homework, we will need to import a library. You only need to execute the following cell once; you don't need to copy this in every cell you run.

In [2]:
import numpy 

# Exercise 1

Using `numpy` and its functions:

a) Create an array of 100 elements all equal to 1, assign the array to a variable named `one_array`, and print it.

In [3]:
# YOUR CODE HERE
one_array = numpy.ones(100)
print(one_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


b) Create an array of 50 elements all equal to 0, assign the array to a variable named `zero_array`, and print it.

In [4]:
# YOUR CODE HERE
zero_array = numpy.zeros(50)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


c) Create an array that starts with the element `3`, ends in `99`, and steps by `2` (i.e., 3 5 7 ...99). Assign the array to a variable named `first_array`, and print it. 

In [5]:
# YOUR CODE HERE
first_array = numpy.arange(3, 100, 2)
print(first_array)

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]


d) Create an array that starts in `-4`, ends in `4`, and has `41` elements. Assign the array to a variable named `second_array`, and print it. 

In [6]:
# YOUR CODE HERE
second_array = numpy.linspace(-4, 4, 41)
print(second_array)

[-4.  -3.8 -3.6 -3.4 -3.2 -3.  -2.8 -2.6 -2.4 -2.2 -2.  -1.8 -1.6 -1.4
 -1.2 -1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1.   1.2  1.4
  1.6  1.8  2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6  3.8  4. ]


# Exercise 2 

Given the following one-dimensional `numpy` arrays:

In [7]:
x = numpy.array([39, 48, 15, 54, 44, 25,  3, 46, 45, 19, 20, 37, 25,  4, 25, 46, 10,
                49, 11, 26, 44, 15, 38,  0, 10, 53, 19, 34, 51, 26, 54, 11, 16])

y = numpy.array([47,  9, 54,  3, 51, 61, 13, 21,  9, 38, 16, 10, 18,  8, 64,  3, 46,
                12, 56,  2,  6, 32, 63, 64, 61, 21, 46, 59, 23,  9, 44, 19, 25])

a) Create an array named `sum_xy` that is the result of adding `x` and `y`, and print it. 

In [8]:
# YOUR CODE HERE
sum_xy = x + y
print(sum_xy)

[ 86  57  69  57  95  86  16  67  54  57  36  47  43  12  89  49  56  61
  67  28  50  47 101  64  71  74  65  93  74  35  98  30  41]


b) Create an array named `diff_xy` that is the result of subtracting `y` from `x`, and print it. 

In [9]:
# YOUR CODE HERE
diff_xy = x - y
print(diff_xy)

[ -8  39 -39  51  -7 -36 -10  25  36 -19   4  27   7  -4 -39  43 -36  37
 -45  24  38 -17 -25 -64 -51  32 -27 -25  28  17  10  -8  -9]


c) Create an array named `op_array` that is the result of the operation below, and print it.

\begin{equation}
    \frac{x^2}{2} + \left(\frac{y}{3}\right)^2 
\end{equation}

In [10]:
# YOUR CODE HERE
op_array = x**2 / 2 +(y/3)**2
print(op_array)

[1005.94444444 1161.          436.5        1459.         1257.
  725.94444444   23.27777778 1107.         1021.5         340.94444444
  228.44444444  695.61111111  348.5          15.11111111  767.61111111
 1059.          285.11111111 1216.5         408.94444444  338.44444444
  972.          226.27777778 1163.          455.11111111  463.44444444
 1453.5         415.61111111  964.77777778 1359.27777778  347.
 1673.11111111  100.61111111  197.44444444]


# Exercise 3 

Given the following array:

In [11]:
arr = numpy.array([22, 13, 54, 35, 76, 17, 68, 49, 19])

a) Using `[ ]`, access the first, fifth and last elements, add them, assign the result to a varaible named `res`, and print it. 

In [12]:
# YOUR CODE HERE
res = arr[0] + arr[4] +arr[-1]
print(res)

117


b) Using slicing, grab a slice that goes from the first to the third element (included), asign it to a variable named `slice_1`, and print it.  

In [13]:
# YOUR CODE HERE
slice_1 = arr[0:3] 
print(slice_1)

[22 13 54]


c) Using slicing, grab the slice that contains the three elements in the middle of `arr`, assign the resulting array to a variable named `slice_mid`. Then,  subtract `17` from all the elements in `slice_mid` (do not use `for` statements), assign the result to a variable named `slice_mid_17`, and print both `slice_mid` and `slice_mid_17`.

In [14]:
# YOUR CODE HERE
slice_mid = arr[3:6]
slice_mid_17 = slice_mid - 17
print(slice_mid)
print(slice_mid_17)

[35 76 17]
[18 59  0]


d) Using slicing, create an array that is the result of adding the first three elements with the last three elements, assign it to a variable named `slice_sum`, and print it. 

In [15]:
# YOUR CODE HERE
slice_sum = arr[0:3] + arr[-3:]
print(slice_sum)

[90 62 73]


## Remember!!

Before you turn this problem in, make sure everything runs as expected. First, restart the kernel (in the menubar, select Kernel→→Restart) and then run all cells (in the menubar, select Cell→→Run All).

Make sure you filled in any place that says YOUR CODE HERE or "YOUR ANSWER HERE", as well as your name at the beggining of the notebook.
