Before you turn in this homework, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you execute every single code cell, in order, filling with your solutions in any place that says `YOUR CODE HERE`, and always DELETE the line that says:

```python
raise NotImplementedError()
```
The purpose of this line is to tell you if you forgot to answer a question (it will throw an error if the line is there)

**IMPORTANT**: DO NOT DELETE ANY CELL.

Fill your name below:

In [2]:
NAME = "Zeyu Liu"

## Before you start 

For this homework, we will need to import a library. You only need to execute the following cell once; you don't need to copy this in every cell you run.

In [3]:
import numpy 

# Exercise 1

Given the following two-dimensional numpy array:

In [4]:
primes = numpy.array([[2, 17, 41, 37], [3, 5, 11, 13], [19, 23, 61, 73], [73, 89, 47, 59]])
print(primes)

[[ 2 17 41 37]
 [ 3  5 11 13]
 [19 23 61 73]
 [73 89 47 59]]


a) Compute the length, shape and type of the `primes` array, assign them to variables named `primes_len`, `primes_shape` and `primes_type`, respectively, and print them. 

In [8]:
# YOUR CODE HERE
primes_len = len(primes)
primes_shape = numpy.shape(primes)
primes_type = type(primes)
print(primes_len)
print(primes_shape)
print(primes_type)

4
(4, 4)
<class 'numpy.ndarray'>


b) Using `[]`, access the first element of the third column, asssign it to a variable named `var_1`, and print the value of `var_1`. 

In [9]:
# YOUR CODE HERE
var_1 = primes[0][2]
print(var_1)

41


c) Using `[]`, access the third element of the fourth column, asssign it to a variable named `var_2`, and print the value of `var_2`. 

In [10]:
# YOUR CODE HERE
var_2 = primes[2][3]
print(var_2)

73


d) Using `[]`, access the second element of the second row, asssign it to a variable named `var_3`, and print the value of `var_3`. 

In [11]:
# YOUR CODE HERE
var_3 = primes[1][1]
print(var_3)

5


e) Using `[]`, access the fourth element of the first row, asssign it to a variable named `var_4`, and print the value of `var_4`.

In [12]:
# YOUR CODE HERE
var_4 = primes[0][3]
print(var_4)

37


# Exercise 2

Given the `primes` array, use slicing to solve the following problems.

In [13]:
primes = numpy.array([[2, 17, 41, 37], [3, 5, 11, 13], [19, 23, 61, 73], [73, 89, 47, 59]])
print(primes)

[[ 2 17 41 37]
 [ 3  5 11 13]
 [19 23 61 73]
 [73 89 47 59]]


a) Grab the second row, assign it to a variable named `second_row`, and print it. 

In [24]:
# YOUR CODE HERE
second_row = primes[1,:]
print(second_row)

[ 3  5 11 13]


b) Grab the last column, assign it to a variable named `last_column`, and print it.

In [25]:
# YOUR CODE HERE
last_column = primes[:,3]
print(last_column)

[37 13 73 59]


c) Grab the slice corresponding to the 2-by-2 top-left block of `primes`, assign it to a variable named `top_left`, and print it.

In [27]:
# YOUR CODE HERE
top_left = primes[0:2,0:2]
print(top_left)

[[ 2 17]
 [ 3  5]]


d) Grab the slice corresponding to the 2-by-2 bottom-right block of `primes`, assign it to a variable named `bot_right`, and print it.

In [28]:
# YOUR CODE HERE
bot_right = primes[-2:,-2:]
print(bot_right)

[[61 73]
 [47 59]]


e) Grab the slice that corresponds to all the elements except the first row and last column, assign it to a variable named `corner`, and print it. 

In [30]:
# YOUR CODE HERE
corner = primes[1:,:-1]
print(corner)

[[ 3  5 11]
 [19 23 61]
 [73 89 47]]


f) Grab the slice corresponding to the 2-by-2 bottom-left block of `primes`, assign it to a variable named `bot_left`. Grab the slice that corresponds to the four elements in the top-right block, assign it to a variable named `top_right`. Create a new variable named `sum_mat` that is the result of adding `bot_left` and `top_right`, and finally print `sum_mat`.  

In [31]:
# YOUR CODE HERE
bot_left = primes[-2:,0:2]
top_right = primes[0:2,-2:]
sum_mat = bot_left + top_right
print(sum_mat)

[[ 60  60]
 [ 84 102]]


# Exercise 3

a) Using `numpy.linspace()` create an array with 51 elements that go from  `-3` to `3`, and assign it to a variable named `x`. 

In [34]:
# YOUR CODE HERE
x = numpy.linspace(-3,3,51)

b) Create an array named `y_pos` that results from the following operation:

\begin{equation}
    y_{pos} = \sqrt{R^2 - x^2}
\end{equation}


where `R=3`.  

*Tip:* 
For the square root use the `numpy` function `numpy.sqrt()`. 

In [37]:
# YOUR CODE HERE
R = 3
y_pos = numpy.sqrt(R**2 - x**2)

## Remember!!

Before you turn this problem in, make sure everything runs as expected. First, restart the kernel (in the menubar, select Kernel→→Restart) and then run all cells (in the menubar, select Cell→→Run All).

Make sure you filled in any place that says YOUR CODE HERE or "YOUR ANSWER HERE", as well as your name at the beggining of the notebook.
